version: "3.8"

services:
  app:
    build: .
    container_name: library_app
    image: shelnaop93/fastapi-mysql-library
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:   # Load environment variables from the .env file
      - .env
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: library_db
    restart: always
    env_file:   # Load environment variables from the .env file
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
